version: "3.5"
services:
  geth:
    build:
      args:
        NETWORK: sepolia
        P2P_PORT: 35415
    ports:
      - 35415:35415/tcp
      - 35415:35415/udp
    image: geth.sepolia-geth.dnp.dappnode.eth:0.1.3
