version: "3.5"
services:
  geth:
    build:
      args:
        NETWORK: holesky
    environment:
      P2P_PORT: 31403
    ports:
      - 31403:31403/tcp
      - 31403:31403/udp
    image: geth.holesky-geth.dnp.dappnode.eth:0.1.2
