version: "3.5"
services:
  geth:
    build:
      args:
        NETWORK: lukso
        P2P_PORT: 33141
    ports:
      - 33141:33141/tcp
      - 33141:33141/udp
    image: geth.lukso-geth.dnp.dappnode.eth:0.1.3
