name: Proof of Attestation

on:
  repository_dispatch:
    types: [tropibot-attestation-test]
  workflow_dispatch:
    inputs:
      consensus_client:
        description: "Consensus Client"
        required: true
        type: choice
        options: [lodestar, teku, prysm, nimbus, lighthouse]

jobs:
  attestation-test:
    uses: dappnode/workflows/.github/workflows/staking-attestation-test.yml@master
    with:
      execution_client: "geth"
      consensus_client: ${{ github.event.client_payload.consensus_client || inputs.consensus_client || '' }}
      pr_number: ${{ github.event.client_payload.pr_number || github.event.pull_request.number || '' }}
      head_ref: ${{ github.event.client_payload.head_ref || github.event.pull_request.head.ref || github.ref_name }}
      sender: ${{ github.event.client_payload.sender || github.event.pull_request.user.login || github.actor }}
    secrets: inherit
