name: Execution Client Sync Test

on:
  workflow_dispatch:
    inputs:
      consensus_client:
        description: "Consensus Client"
        required: true
        type: choice
        options: [lodestar, teku, prysm, nimbus, lighthouse]
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

jobs:
  sync-test:
    uses: dappnode/workflows/.github/workflows/staking-sync-test.yml@master
    with:
      execution_client: "geth"
      consensus_client: ${{ inputs.consensus_client || '' }}
    secrets: inherit
