name: Execution Client Sync Production

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      consensus_client:
        description: "Consensus Client"
        required: true
        type: choice
        options: [lodestar, teku, prysm, nimbus, lighthouse]

jobs:
  sync:
    uses: dappnode/workflows/.github/workflows/sync-production.yml@master
    with:
      execution_client: "geth"
      consensus_client: ${{ inputs.consensus_client || '' }}
    secrets: inherit
